output   = "storage/mysql/models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "simple_invoicing"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "jLiEo34@3!%k"
  sslmode = "false"
  tinyint_as_int = true