apiVersion: v1
kind: Service
metadata:
  name: dddstructure-api-service
spec:
  selector:
    app: dddstructure
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000