apiVersion: apps/v1
kind: Deployment
metadata:
  name: dddstructure-mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: dddstructure-secrets
              key: db-name
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dddstructure-secrets
              key: db-pass
      volumes:
      - name: mysql-initdb
        persistentVolumeClaim:
          claimName: mysql-initdb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dddstructure-mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306