apiVersion: apps/v1
kind: Deployment
metadata:
  name: dddstructure-api-deployment
  labels:
    app: dddstructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dddstructure
  template:
    metadata:
      labels:
        app: dddstructure
    spec:
      containers:
      - name: dddstructure
        image: dddstructure:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dddstructure-configmap
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dddstructure-configmap
              key: db-port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dddstructure-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dddstructure-secrets
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dddstructure-secrets
              key: db-pass