apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
  - name: mysql-initdb
    persistentVolumeClaim:
      claimName: mysql-initdb-pv-claim
  containers:
  - name: task-pv-container
    image: debian:bookworm-slim
    volumeMounts:
    - name: mysql-initdb
      mountPath: /docker-entrypoint-initdb.d